### ISSUE TITLE
Not possible to configure Rearranger

### ISSUE THREAD

**Issue by sdyson** [DaveKriewall/Rearranger#1]
Since the upgrade to IntelliJ 2016 it is no longer possible to configure Rearranger. The attached screenshot shows that searching for rearranger in the settings dialog produces no results. Rearranger is otherwise still working using my previously configured settings. 

![rearranger](https://cloud.githubusercontent.com/assets/288979/20515097/d3bdaf12-b087-11e6-9a73-0d54cea429d4.png)

**Comment by SuzanaK** [comment]
I have the same problem and since it's a new install of the plugin, I cannot use it at all. Trying Edit-Rearrange or using the shortcut I get the following stacktrace:

> 
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
> 	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:356)
> 	at com.wrq.rearranger.ProjectTreeActionHandler$RearrangeIt.<init>(ProjectTreeActionHandler.java:128)
> 	at com.wrq.rearranger.ProjectTreeActionHandler$1.run(ProjectTreeActionHandler.java:76)
> 	at java.lang.Thread.run(Thread.java:745)
> [ 436892]  ERROR - ellij.ide.impl.DataManagerImpl - IntelliJ IDEA 2016.2  Build #IU-162.1121.32 
> [ 436892]  ERROR - ellij.ide.impl.DataManagerImpl - JDK: 1.8.0_76-release 
> [ 436892]  ERROR - ellij.ide.impl.DataManagerImpl - VM: OpenJDK 64-Bit Server VM 
> [ 436893]  ERROR - ellij.ide.impl.DataManagerImpl - Vendor: JetBrains s.r.o 
> [ 436893]  ERROR - ellij.ide.impl.DataManagerImpl - OS: Linux 
> [ 436893]  ERROR - ellij.ide.impl.DataManagerImpl - Last Action: RearrangeProjectTree 
> [ 436893]  ERROR - ellij.ide.impl.DataManagerImpl - cannot share data context between Swing events; initial event count = 264524; current event count = 264525 
>

**Comment by ChargingBulle** [comment]
Code arrangement is suppoted by IntelliJ even without using a Plugin as far as I know

More Information:
[Rearranging Code Using Arrangement Rules](https://www.jetbrains.com/help/idea/2016.3/rearranging-code-using-arrangement-rules.html)
[Menu: Arrangement](https://www.jetbrains.com/help/idea/2016.3/code-style-java.html#d48201e1735)
![](http://i.imgur.com/HTYiIwU.png)

**Comment by sdyson** [comment]
I experimented using the Arrangement feature in IntelliJ but unfortunately it is not as powerful as Rearranger. Specifically, Rearranger supports grouping methods by interface with a separator comment between each interface.

**Comment by beccari** [comment]
I am experiencing the same problem and I agreed with @sdyson 
The rearranger way was elected by the team as coding formatting standards.
Any chance we get this issue fixed?

**Comment by thhart** [comment]
Here the same: configuration is lost/hidden in 2017.1. By the way the options are found in following file of the Idea settings: config/options/other.xml. I shared mine with team partners to sync arranging.

**Comment by itajun** [comment]
I've submitted a [pull request](https://github.com/DaveKriewall/Rearranger/pull/3) to the Author with a fix. Idea >=2016 requires a separate entry in the plugin.xml file. I've added this and kept the rest of the plugin intact. It's a great plugin and it'd be a shame to let it die.
Until the author merges the request, you can download the fixed version from here:
[https://github.com/itajun/Rearranger/blob/master/Rearranger.jar](https://github.com/itajun/Rearranger/blob/master/Rearranger.jar)
Thanks Dave for the great work with this plugin. I even postponed my upgrade of Idea when I noticed the issue, this is how important this feature is to my sanity :D.

![image](https://user-images.githubusercontent.com/7754697/29999142-c840dd42-9080-11e7-9c0e-599b049f0ba3.png)
